### ISSUE TITLE
Kivy webview about youtube

### ISSUE THREAD

**Issue by CZacVV** [Android-for-Python/Webview-Example#1]
Hi , I'm Youtube channel fan .
I turn a webview apk install on my phone , and open this page.
--> https://support.google.com/youtube/answer/171780
webview app youtube embed fullscreen button is disable , do you know how unlock it ? 

apk install
![IMG_20210808_001231](https://user-images.githubusercontent.com/88590721/128606986-a1bfbfbc-7eb7-48b7-81ae-0bb7673e62d8.jpg)
open app
![IMG_20210808_001310](https://user-images.githubusercontent.com/88590721/128606996-c4a06a7c-3d29-414f-bee7-76f70573d8db.jpg)
Kivy webview open youtube embed page , fullscreen button disable .
![IMG_20210808_001607](https://user-images.githubusercontent.com/88590721/128607013-aa3dcc24-0ded-47ce-acef-5de3a42c84b4.jpg)
Android Chrome open same page , youtube embed fullscreen button is normally.
![IMG_20210808_001733](https://user-images.githubusercontent.com/88590721/128607260-cdd059ba-5df1-4f50-8b7c-e4263dbb1b31.jpg)

**Comment by Android-for-Python** [comment]
No idea
Webview is part of Android `WebViewA = autoclass('android.webkit.WebView')` 
I'd suggest searching the Android documentation.
