### ISSUE TITLE
Motion Events in webview

### ISSUE THREAD

**Issue by git-bone** [Android-for-Python/Webview-Example#2]
Hi
any chance you have motion events working in webview? I can get on_touch_move working during splash screen, but after the web page is loaded, it all stops.

The use case would be 'pulldown' for page refresh, and swipe left/right for pagination. 

thanks!

**Comment by Android-for-Python** [comment]
Inside the ModalView is an android.view.view not a Kivy layout or widget. Kivy touch events are not going to work there as Kivy does not own the screen.
So for example the back gesture detect is a PythonJavaClass. 

The pdfview-example has some other Android gesture detectors. https://github.com/Android-for-Python/PDFview-Example/blob/main/pdfview.py . 

I have not tried to do what you want to do, but if it is possible then the pieces you need are probably in pdfview.

**Comment by git-bone** [comment]
Wow. Thanks!

 I did try with PythonJavaClass like with the back function,  something similar as your link actually, but got NotImplementedErrors from pyjinius. I do see some differences in my attempts and the solution in your link so I'll need to see where I went wrong.

**Comment by git-bone** [comment]
yes it works. Almost 100% copy paste actually, to get the touch events working. It detects them all nicely. thanks! 

now I'm stuck on the method for webview.evaluateJavascript, I'm struggling on getting the result of this function, where the javascript should return innerHTML of an element. How to get the return value.  Probable I need some kind of wrapper to use this java function?

**Comment by Android-for-Python** [comment]
Never tried this but it looks like evaluateJavascript doesn't return a result.
However one of its arguments a ValueCallback returns the result via onReceiveValue() which  is abstract.
So the result is asynchronous.

That is as detailed as I looked, I expect you are right about the wrapper.

I can sort of point you in the right direction (I think) with this example.

Please don't ask me about details, I really don't want to load this stuff into my head again as I have other things to do.

Create a Java interface (perhaps CallbackWrapper implements ValueCallback ?????)
https://github.com/Android-for-Python/Face-Detect-Example/blob/main/mlkit_src/org/kivy/mlkit/CallbackWrapper.java

And a Python implementation of onRecieveValue
https://github.com/Android-for-Python/Face-Detect-Example/blob/main/mlkit_src/org/kivy/mlkit/CallbackWrapper.java

Instantiate the Python Wrapper with the Python method you want to call onRecieveValue
https://github.com/Android-for-Python/Face-Detect-Example/blob/main/facedetect.py#L61

Set the instantiation as a listener
https://github.com/Android-for-Python/Face-Detect-Example/blob/main/facedetect.py#L64

**Comment by git-bone** [comment]
hi, thanks for the support so far, really appreciate it. Don't know that much about java and android development. I'm learning but not capable yet of figuring this out quickly. However, I solved my problem with the javascript by calling webview.loadUrl(javascript:... 
for the long run I'm still interested in figuring out about that listener, but let me close this issue for now.
